-- Wallpaper-synced theme: tokyonight recolored from matugen output.
-- The `matugen-colors` module is GENERATED by matugen on every wallpaper
-- change (templates/nvim.lua -> ~/.config/nvim/lua/matugen-colors.lua).
-- It is deliberately NOT vendored in modules/: activation rsync would
-- otherwise overwrite the live colors with a stale copy on each rebuild.
-- Before the first matugen run (pcall fails) this is a no-op and LazyVim
-- keeps its tokyonight default from plugins/colorscheme.lua.
return {
  {
    "folke/tokyonight.nvim",
    opts = function(_, opts)
      local ok, m = pcall(require, "matugen-colors")
      if not ok or type(m) ~= "table" or type(m.colors) ~= "table" then
        return
      end
      local c = m.colors
      opts.on_colors = function(colors)
        if c.bg then
          colors.bg = c.bg
          colors.bg_dark = c.bg
          colors.bg_float = c.surface or c.bg
          colors.bg_highlight = c.surface or c.bg
          colors.bg_popup = c.surface or c.bg
          colors.bg_search = c.surface or c.bg
          colors.bg_sidebar = c.bg
          colors.bg_statusline = c.bg
          colors.black = c.bg
        end
        if c.fg then
          colors.fg = c.fg
          colors.fg_dark = c.fg
          colors.fg_float = c.fg
          colors.fg_gutter = c.outline or c.fg
          colors.fg_sidebar = c.fg
        end
        if c.outline then
          colors.border = c.outline
          colors.comment = c.outline
          colors.dark3 = c.outline
          colors.dark5 = c.outline
        end
        if c.primary then
          colors.blue = c.primary
          colors.magenta = c.primary
        end
        if c.secondary then
          colors.cyan = c.secondary
          colors.teal = c.secondary
        end
        if c.tertiary then
          colors.green = c.tertiary
        end
        if c.error then
          colors.red = c.error
          colors.red1 = c.error
        end
      end
    end,
  },
}
